const Minio = require('minio');

// Initialize MinIO client
const minioClient = new Minio.Client({
  endPoint: process.env.MINIO_ENDPOINT || 'localhost',
  port: parseInt(process.env.MINIO_PORT) || 9000,
  useSSL: process.env.MINIO_USE_SSL === 'true',
  accessKey: process.env.MINIO_ACCESS_KEY || 'minioadmin',
  secretKey: process.env.MINIO_SECRET_KEY || 'minioadmin'
});

const BUCKET_NAME = process.env.MINIO_BUCKET_NAME || 'foligo';
const MINIO_PUBLIC_URL = process.env.MINIO_PUBLIC_URL || `http://localhost:9000/${BUCKET_NAME}`;

// Ensure bucket exists
async function ensureBucket() {
  try {
    const exists = await minioClient.bucketExists(BUCKET_NAME);
    if (!exists) {
      await minioClient.makeBucket(BUCKET_NAME, 'us-east-1');
      console.log(`✅ Created MinIO bucket: ${BUCKET_NAME}`);
      
      // Try to set bucket policy to allow public read access
      try {
        const policy = {
          Version: '2012-10-17',
          Statement: [
            {
              Effect: 'Allow',
              Principal: { AWS: ['*'] },
              Action: ['s3:GetObject'],
              Resource: [`arn:aws:s3:::${BUCKET_NAME}/*`]
            }
          ]
        };
        await minioClient.setBucketPolicy(BUCKET_NAME, JSON.stringify(policy));
        console.log(`✅ Set public read policy for bucket: ${BUCKET_NAME}`);
      } catch (policyError) {
        // If policy setting fails, it's okay - bucket is still created
        console.warn('Could not set bucket policy (this is okay if using anonymous download):', policyError.message);
      }
    }
  } catch (error) {
    console.error('Error ensuring MinIO bucket:', error);
    throw error;
  }
}

// Upload file to MinIO
async function uploadFile(fileBuffer, objectName, mimeType) {
  try {
    await ensureBucket();
    
    const metaData = {
      'Content-Type': mimeType
    };

    await minioClient.putObject(BUCKET_NAME, objectName, fileBuffer, fileBuffer.length, metaData);
    
    // Return objectName only - URL will be generated by the API route
    return objectName;
  } catch (error) {
    console.error('Error uploading file to MinIO:', error);
    throw error;
  }
}

// Delete file from MinIO
async function deleteFile(objectName) {
  try {
    await minioClient.removeObject(BUCKET_NAME, objectName);
    return true;
  } catch (error) {
    console.error('Error deleting file from MinIO:', error);
    throw error;
  }
}

// Get file URL (public URL)
function getFileUrl(objectName) {
  return `${MINIO_PUBLIC_URL}/${objectName}`;
}

// Check if file exists
async function fileExists(objectName) {
  try {
    await minioClient.statObject(BUCKET_NAME, objectName);
    return true;
  } catch (error) {
    if (error.code === 'NotFound') {
      return false;
    }
    throw error;
  }
}

module.exports = {
  minioClient,
  uploadFile,
  deleteFile,
  getFileUrl,
  fileExists,
  ensureBucket,
  BUCKET_NAME
};

