-- Expand user_profiles with the full autofill field taxonomy (Personal Info,
-- Location, Education, Experience, EEO, Work Authorization, Social & Links, Other)
-- so the GoApply extension can autofill the same breadth of job-application
-- form fields as the field categories it now recognizes.

ALTER TABLE "user_profiles"
  ADD COLUMN "firstName" TEXT,
  ADD COLUMN "lastName" TEXT,
  ADD COLUMN "middleName" TEXT,
  ADD COLUMN "preferredName" TEXT,
  ADD COLUMN "legalName" TEXT,
  ADD COLUMN "username" TEXT,
  ADD COLUMN "phoneType" TEXT,
  ADD COLUMN "phoneCountry" TEXT,
  ADD COLUMN "birthday" TEXT,
  ADD COLUMN "pronouns" TEXT,
  ADD COLUMN "address" TEXT,
  ADD COLUMN "address2" TEXT,
  ADD COLUMN "city" TEXT,
  ADD COLUMN "state" TEXT,
  ADD COLUMN "country" TEXT,
  ADD COLUMN "postalCode" TEXT,
  ADD COLUMN "highestDegree" TEXT,
  ADD COLUMN "school" TEXT,
  ADD COLUMN "discipline" TEXT,
  ADD COLUMN "gpa" TEXT,
  ADD COLUMN "educationSummary" TEXT,
  ADD COLUMN "language" TEXT,
  ADD COLUMN "currentCompany" TEXT,
  ADD COLUMN "currentTitle" TEXT,
  ADD COLUMN "currentlyWorking" BOOLEAN,
  ADD COLUMN "experienceSummary" TEXT,
  ADD COLUMN "yearsExperience" TEXT,
  ADD COLUMN "gender" TEXT,
  ADD COLUMN "ethnicity" TEXT,
  ADD COLUMN "hispanicLatino" TEXT,
  ADD COLUMN "veteranStatus" TEXT,
  ADD COLUMN "disabilityStatus" TEXT,
  ADD COLUMN "lgbtStatus" TEXT,
  ADD COLUMN "over18" BOOLEAN,
  ADD COLUMN "over21" BOOLEAN,
  ADD COLUMN "hasDriversLicense" BOOLEAN,
  ADD COLUMN "workAuthUS" TEXT,
  ADD COLUMN "workAuth" TEXT,
  ADD COLUMN "sponsorshipRequired" TEXT,
  ADD COLUMN "twitter" TEXT,
  ADD COLUMN "behance" TEXT,
  ADD COLUMN "dribbble" TEXT,
  ADD COLUMN "website" TEXT,
  ADD COLUMN "desiredSalary" TEXT,
  ADD COLUMN "referredBy" TEXT,
  ADD COLUMN "source" TEXT;
