<template>
  <div class="p-6 max-w-6xl mx-auto">
    <button class="text-primary-400 hover:text-primary-300 mb-6" @click="router.push('/admin/content')">← Back to content</button>
    <div v-if="loading" class="text-center py-20 text-gray-400">Loading content…</div>
    <div v-else-if="!item" class="bg-gray-800 border border-gray-700 rounded-lg p-10 text-center text-white">Content not found</div>
    <template v-else>
      <div class="flex flex-wrap justify-between gap-4 mb-6"><div><div class="flex items-center gap-3"><h1 class="text-3xl font-bold text-white">{{ item.title || 'Untitled' }}</h1><span class="px-2 py-1 text-xs bg-blue-600 text-white rounded">{{ item.contentType }}</span><span :class="item.status === 'PUBLISHED' ? 'bg-green-600' : 'bg-gray-600'" class="px-2 py-1 text-xs text-white rounded">{{ item.status }}</span></div><p v-if="item.excerpt" class="text-gray-400 mt-3 max-w-3xl">{{ item.excerpt }}</p></div><button class="px-4 py-2 bg-primary-600 hover:bg-primary-500 text-white rounded-lg self-start" @click="editing = !editing">{{ editing ? 'Cancel' : 'Edit details' }}</button></div>
      <form v-if="editing" class="bg-gray-800 border border-gray-700 rounded-lg p-6 mb-6 grid gap-4 md:grid-cols-3" @submit.prevent="saveContent"><label class="text-sm text-gray-300 md:col-span-2">Title<input v-model="form.title" required class="mt-2 w-full px-3 py-2 bg-gray-900 border border-gray-700 rounded text-white" /></label><label class="text-sm text-gray-300">Status<select v-model="form.status" class="mt-2 w-full px-3 py-2 bg-gray-900 border border-gray-700 rounded text-white"><option>DRAFT</option><option>PUBLISHED</option><option>HIDDEN</option><option>REVISION</option></select></label><div class="md:col-span-3"><button :disabled="saving" class="px-4 py-2 bg-primary-600 text-white rounded-lg disabled:opacity-50">{{ saving ? 'Saving…' : 'Save changes' }}</button></div></form>
      <div class="grid gap-6 lg:grid-cols-3"><article class="lg:col-span-2 bg-gray-800 border border-gray-700 rounded-lg p-6"><h2 class="text-lg font-semibold text-white mb-4">Content</h2><div v-if="item.content" class="whitespace-pre-wrap break-words text-gray-200 leading-7">{{ item.content }}</div><p v-else class="text-gray-400">This item has no body content.</p></article><aside class="space-y-6"><section class="bg-gray-800 border border-gray-700 rounded-lg p-6"><h2 class="text-lg font-semibold text-white mb-4">Portfolio</h2><button class="text-left" @click="router.push(`/admin/projects/${item.project.id}`)"><span class="block text-white hover:text-primary-300">{{ item.project.name }}</span><span v-if="item.project.subdomain" class="text-sm text-gray-400">{{ item.project.subdomain }}.foligo.tech</span></button></section><section class="bg-gray-800 border border-gray-700 rounded-lg p-6"><h2 class="text-lg font-semibold text-white mb-4">Owner</h2><button class="text-left" @click="router.push(`/admin/users/${item.project.owner.id}`)"><span class="block text-white hover:text-primary-300">{{ item.project.owner.name }}</span><span class="text-sm text-gray-400">{{ item.project.owner.email }}</span></button></section><section class="bg-gray-800 border border-gray-700 rounded-lg p-6 text-sm text-gray-400 space-y-2"><p>Slug: <span class="text-gray-200">{{ item.slug || '—' }}</span></p><p>Created: <span class="text-gray-200">{{ formatDate(item.createdAt) }}</span></p><p>Updated: <span class="text-gray-200">{{ formatDate(item.updatedAt) }}</span></p></section></aside></div>
    </template>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useToast } from 'vue-toastification'; import api from '@/services/api'
const route = useRoute(); const router = useRouter(); const toast = useToast(); const loading = ref(true); const saving = ref(false); const editing = ref(false); const item = ref<any>(null); const form = reactive({ title: '', status: 'DRAFT' })
const formatDate = (v: string) => new Date(v).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })
const load = async () => { try { const { data } = await api.get(`/admin/content/${route.params.id}`); item.value = data; Object.assign(form, { title: data.title, status: data.status }) } catch (e: any) { toast.error(e.response?.data?.message || 'Failed to load content') } finally { loading.value = false } }
const saveContent = async () => { try { saving.value = true; const { data } = await api.put(`/admin/content/${route.params.id}`, form); item.value = { ...item.value, ...data }; editing.value = false; toast.success('Content updated') } catch (e: any) { toast.error(e.response?.data?.message || 'Failed to update content') } finally { saving.value = false } }
onMounted(load)
</script>
